#!/bin/bash

echo " -> Removing docker images"
docker rm -vf nxing1

echo " -> Rebuilding the image from current directory"
docker build -t heroku-docker-nginx .

echo " -> Run the slave container"

docker run -d --name nxing1 \
  --env PORT=80 \
  --env APP1_URL=http://localhost:5000 \
  -p 3001:80 \
  heroku-docker-nginx

docker ps
echo " -> Done. To shell into the container: docker exec -i -t nxing1 bash"

docker exec -i -t nxing1 cat /etc/nginx/conf.d/default.conf
